services:

  dashboard:
    container_name: dashboard
    extends:
      file:  EScootersManagementSystemDashboard/docker-compose.dashboard.yml
      service: dashboard-service
    ports:
      - "3000:3000"
    networks:
      - gateway-network
    volumes:
      - logs:/app/logs
    restart: always


  api-gateway:
    container_name: api-gateway
    extends:
      file: APIGateway/docker-compose.apigateway.yml
      service: api-gateway
    networks:
      - gateway-network
      - escooters-network
      - users-network
      - rides-network
    volumes:
      - logs:/app/logs
    restart: always


  escooters-service:
    container_name: escooters-service
    extends:
      file: EScootersService/docker-compose.escooters.yml
      service: escooters-service
    depends_on:
      escooters-db:
        condition: service_healthy
    networks:
      - escooters-network
      - escooters-db-network
    volumes:
      - logs:/app/logs
    restart: always

  escooters-db:
    container_name: escooters-db
    extends:
      file: EScootersService/docker-compose.escooters.yml
      service: escooters-db
    networks:
      - escooters-db-network
    restart: always


  users-service:
    container_name: users-service
    extends:
      file: UsersService/docker-compose.users.yaml
      service: users-service
    depends_on:
      users-db:
        condition: service_healthy
    networks:
      - users-network
      - users-db-network
    volumes:
      - logs:/app/logs
    restart: always

  users-db:
    container_name: users-db
    extends:
      file: UsersService/docker-compose.users.yaml
      service: users-db
    restart: always
    networks:
      - users-db-network


  rides-service:
    container_name: rides-service
    extends:
      file: RidesService/docker-compose.rides.yml
      service: rides-service
    depends_on:
      rides-db:
        condition: service_healthy
    networks:
      - rides-db-network
      - rides-network
    volumes:
      - logs:/app/logs
    restart: always

  rides-db:
    container_name: rides-db
    extends:
      file: RidesService/docker-compose.rides.yml
      service: rides-db
    restart: always
    networks:
      - rides-db-network

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - grafana-prom
      - gateway-network
      - escooters-network
      - users-network
      - rides-network

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Set a password for the Grafana admin user
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - grafana-prom

  elk:
    image: sebp/elk:8.13.4
    ports:
      - "5601:5601" # Kibana
      - "9200:9200" # Elasticsearch
      - "5044:5044" # Logstash
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.22
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs:/app/logs:ro
    networks:
      - elk
    depends_on:
      - elk

networks:
  gateway-network:
  escooters-network:
  escooters-db-network:
  users-network:
  users-db-network:
  rides-network: 
  rides-db-network: 
  grafana-prom:
  elk:

volumes:
  grafana-storage:
  logs:
