services:
  dashboard:
    extends:
      file:  EScootersManagementSystemDashboard/docker-compose.dashboard.yml
      service: dashboard-service
    ports:
      - "3000:3000"
    networks:
      - gateway-network
    restart: always
  api-gateway:
    extends:
      file: APIGateway/docker-compose.apigateway.yml
      service: api-gateway
    restart: always
    networks:
      - gateway-network
      - escooters-network
      - users-network
      - rides-network
  escooters-service:
    extends:
      file: EScootersService/docker-compose.escooters.yml
      service: escooters-service
    depends_on:
      escooters-db:
        condition: service_healthy
    restart: always
    networks:
      - escooters-network
      - escooters-db-network
  escooters-db:
    extends:
      file: EScootersService/docker-compose.escooters.yml
      service: escooters-db
    networks:
      - escooters-db-network
    restart: always
  users-service:
    extends:
      file: UsersService/docker-compose.users.yaml
      service: users-service
    depends_on:
      users-db:
        condition: service_healthy
    restart: always
    networks:
      - users-network
      - users-db-network
  users-db:
    extends:
      file: UsersService/docker-compose.users.yaml
      service: users-db
    restart: always
    networks:
      - users-db-network
  rides-service:
    extends:
      file: RidesService/docker-compose.rides.yml
      service: rides-service
    depends_on:
      rides-db:
        condition: service_healthy
    restart: always
    networks:
      - rides-db-network
      - rides-network
  rides-db:
    extends:
      file: RidesService/docker-compose.rides.yml
      service: rides-db
    restart: always
    networks:
      - rides-db-network

networks:
  gateway-network:
  escooters-network:
  escooters-db-network:
  users-network:
  users-db-network:
  rides-network: 
  rides-db-network: 

